server:
  port: 1204
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goshopping?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root