server:
  port: 1204
spring:
  application:
    name: goshopping-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goshopping?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
