server:
  port: 1205

spring:
  application:
    name: goshopping-monitor
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      discovery:  # 不显示admin-server的监控信息
        ignored-services: ${spring.application.name}
      ui:
        # 修改网页显示的tab标题
        title: "GoShopping应用监控管理"
        # 修改网页的brand的图标和标题
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>GoShopping应用监控管理</span>"